### ISSUE TITLE
End to End (Nightly) Failure

### ISSUE THREAD

**Issue by dabonnie** [ros-tooling/system_metrics_collector#108]
## Description

The e2e nightly failed: https://github.com/ros-tooling/system_metrics_collector/actions/runs/50903036

## Expected Behavior

The e2e nightly action passes

## Actual Behavior

The e2e test fails (details)

```
[run_e2e_test] [DEBUG] [2020-03-06 17:35:46,656]: Executing: ['ros2', 'launch', 'system_metrics_collector', 'talker_listener_example.launch.py']
[run_e2e_test] [INFO] [2020-03-06 17:35:46,658]: ====Starting tests====
[run_e2e_test] [DEBUG] [2020-03-06 17:35:46,659]: starting test check_for_expected_nodes
[run_e2e_test] [DEBUG] [2020-03-06 17:35:46,659]: execute_command: ['ros2', 'node', 'list']
[INFO] [launch]: All log files can be found below /home/runner/.ros/log/2020-03-06-17-35-47-200362-fv-az78-80908
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught exception when trying to load file of format [py]: Passing both 'node_name' and 'name' parameters. Only use 'name'.
[run_e2e_test] [DEBUG] [2020-03-06 17:35:47,739]: check_for_expected_nodes observed_nodes=['/launch_ros_80908']
/home/runner/work/system_metrics_collector/system_metrics_collector/ros_ws/build/launch_ros/launch_ros/actions/lifecycle_node.py:79: UserWarning: The parameter 'node_name' is deprecated, use 'name' instead
  warnings.warn("The parameter 'node_name' is deprecated, use 'name' instead")
/home/runner/work/system_metrics_collector/system_metrics_collector/ros_ws/build/launch_ros/launch_ros/descriptions/composable_node.py:68: UserWarning: The parameter 'node_plugin' is deprecated, use 'plugin' instead
  warnings.warn("The parameter 'node_plugin' is deprecated, use 'plugin' instead")
/home/runner/work/system_metrics_collector/system_metrics_collector/ros_ws/build/launch_ros/launch_ros/descriptions/composable_node.py:77: UserWarning: The parameter 'node_name' is deprecated, use 'name' instead
  warnings.warn("The parameter 'node_name' is deprecated, use 'name' instead")
/home/runner/work/system_metrics_collector/system_metrics_collector/ros_ws/build/launch_ros/launch_ros/actions/composable_node_container.py:65: UserWarning: The parameter 'node_name' is deprecated, use 'name' instead
  warnings.warn("The parameter 'node_name' is deprecated, use 'name' instead")
[run_e2e_test] [DEBUG] [2020-03-06 17:35:49,742]: starting test check_for_expected_nodes
[run_e2e_test] [DEBUG] [2020-03-06 17:35:49,743]: execute_command: ['ros2', 'node', 'list']
[run_e2e_test] [DEBUG] [2020-03-06 17:35:50,196]: check_for_expected_nodes observed_nodes=[]
[run_e2e_test] [DEBUG] [2020-03-06 17:35:54,201]: starting test check_for_expected_nodes
[run_e2e_test] [DEBUG] [2020-03-06 17:35:54,201]: execute_command: ['ros2', 'node', 'list']
[run_e2e_test] [DEBUG] [2020-03-06 17:35:54,642]: check_for_expected_nodes observed_nodes=[]
[run_e2e_test] [DEBUG] [2020-03-06 17:36:02,651]: starting test check_for_expected_nodes
[run_e2e_test] [DEBUG] [2020-03-06 17:36:02,651]: execute_command: ['ros2', 'node', 'list']
[run_e2e_test] [DEBUG] [2020-03-06 17:36:03,107]: check_for_expected_nodes observed_nodes=[]
[run_e2e_test] [DEBUG] [2020-03-06 17:36:19,123]: starting test check_for_expected_nodes
[run_e2e_test] [DEBUG] [2020-03-06 17:36:19,123]: execute_command: ['ros2', 'node', 'list']
[run_e2e_test] [DEBUG] [2020-03-06 17:36:19,574]: check_for_expected_nodes observed_nodes=[]
[run_e2e_test] [DEBUG] [2020-03-06 17:36:51,590]: starting test check_for_expected_nodes
[run_e2e_test] [DEBUG] [2020-03-06 17:36:51,590]: execute_command: ['ros2', 'node', 'list']
[run_e2e_test] [DEBUG] [2020-03-06 17:36:52,068]: check_for_expected_nodes observed_nodes=[]
[run_e2e_test] [DEBUG] [2020-03-06 17:37:52,128]: starting test check_for_expected_nodes
[run_e2e_test] [DEBUG] [2020-03-06 17:37:52,128]: execute_command: ['ros2', 'node', 'list']
[run_e2e_test] [DEBUG] [2020-03-06 17:37:52,579]: check_for_expected_nodes observed_nodes=[]
[run_e2e_test] [DEBUG] [2020-03-06 17:38:52,632]: starting test check_for_expected_nodes
[run_e2e_test] [DEBUG] [2020-03-06 17:38:52,632]: execute_command: ['ros2', 'node', 'list']
[run_e2e_test] [DEBUG] [2020-03-06 17:38:53,074]: check_for_expected_nodes observed_nodes=[]
[run_e2e_test] [DEBUG] [2020-03-06 17:39:53,113]: starting test check_for_expected_nodes
[run_e2e_test] [DEBUG] [2020-03-06 17:39:53,113]: execute_command: ['ros2', 'node', 'list']
[run_e2e_test] [DEBUG] [2020-03-06 17:39:53,571]: check_for_expected_nodes observed_nodes=[]
[run_e2e_test] [DEBUG] [2020-03-06 17:40:53,631]: starting test check_for_expected_nodes
[run_e2e_test] [DEBUG] [2020-03-06 17:40:53,631]: execute_command: ['ros2', 'node', 'list']
[run_e2e_test] [DEBUG] [2020-03-06 17:40:54,081]: check_for_expected_nodes observed_nodes=[]
[run_e2e_test] [ERROR] [2020-03-06 17:40:54,081]: Test failure: 
Traceback (most recent call last):
  File "ros_ws/src/system_metrics_collector/test/run_e2e_test.py", line 291, in main
[run_e2e_test] [ERROR] [2020-03-06 17:40:54,081]: Test failure: 
Traceback (most recent call last):
  File "ros_ws/src/system_metrics_collector/test/run_e2e_test.py", line 291, in main
    check_for_expected_nodes()
  File "/usr/lib/python3/dist-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/lib/python3/dist-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/lib/python3/dist-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "ros_ws/src/system_metrics_collector/test/run_e2e_test.py", line 159, in check_for_expected_nodes
    ' Observed: ' + str(observed_nodes))
SystemMetricsEnd2EndTestException: Failed to enumerate expected nodes. Observed: []
[run_e2e_test] [DEBUG] [2020-03-06 17:40:54,082]: Finished tests. Sending SIGINT
[run_e2e_test] [DEBUG] [2020-03-06 17:40:54,082]: exiting with test_output=1
##[error]Process completed with exit code 1.
```

## To Reproduce
1. Create a system metrics workspace via ros2 master sources
2. Build with ```colcon build --packages-up-to system_metrics_collector```
3. Source with ```source install/setup.bash && source install/local_setup.bash```
4. Run the e2e test, e.g., ```python3 src/system_metrics_collector/test/run_e2e_test.py```
5. See error

## System (please complete the following information)
 - OS: Ubuntu Bionic
 - ROS2 Distro: [master](https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos)

**Comment by dabonnie** [comment]
Triggered changes via: https://github.com/ros2/launch_ros/pull/122
